# Generated by Django 5.1.4 on 2024-12-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_customer_bankaccount_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='notes',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
