# Generated by Django 5.1.4 on 2024-12-24 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0003_bankaccount_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_names', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=60)),
                ('pub_date', models.DateTimeField(verbose_name='date added')),
                ('date_of_birth', models.DateTimeField()),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('number', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.customer')),
            ],
        ),
    ]
