# Generated by Django 5.1.4 on 2024-12-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_licence'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='licence',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
