# Generated by Django 5.1.4 on 2024-12-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0006_alter_customer_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licence',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
